INSERT INTO ITEMS (ITEM_NAME, COST, INVENTORY, IMAGE_URL) VALUES ('Coke', 10.00 , 120 , 'images/coke.jpg');
INSERT INTO ITEMS (ITEM_NAME, COST, INVENTORY, IMAGE_URL) VALUES ('Pepsi', 13.00 , 112 , 'images/pepsi.jpg');
INSERT INTO ITEMS (ITEM_NAME, COST, INVENTORY, IMAGE_URL) VALUES ('Simba Chips', 15.00 , 812 , 'images/simba.jpg');
INSERT INTO ITEMS (ITEM_NAME, COST, INVENTORY, IMAGE_URL) VALUES ('Lays', 8.00 , 192 , 'images/lays.jpg');
INSERT INTO ITEMS (ITEM_NAME, COST, INVENTORY, IMAGE_URL) VALUES ('Smarties', 5.00 , 212 , 'images/smarties.jpg');
INSERT INTO ITEMS (ITEM_NAME, COST, INVENTORY, IMAGE_URL) VALUES ('Doritos', 15.00 , 312 , 'images/doritos.jpg');
INSERT INTO ITEMS (ITEM_NAME, COST, INVENTORY, IMAGE_URL) VALUES ('Maynards', 10.00 , 292 , 'images/maynards.jpg');
INSERT INTO ITEMS (ITEM_NAME, COST, INVENTORY, IMAGE_URL) VALUES ('Water', 4.00 , 212 , 'images/water.jpg');
INSERT INTO ITEMS (ITEM_NAME, COST, INVENTORY, IMAGE_URL) VALUES ('Biltong', 15.00 , 112 , 'images/biltong.jpg');
INSERT INTO ITEMS (ITEM_NAME, COST, INVENTORY, IMAGE_URL) VALUES ('Noughat', 15.00 , 302 , 'images/noughat.jpg');
INSERT INTO ITEMS (ITEM_NAME, COST, INVENTORY, IMAGE_URL) VALUES ('cheasNaks', 10.00 , 292 , 'images/cheasNaks.jpg');
INSERT INTO ITEMS (ITEM_NAME, COST, INVENTORY, IMAGE_URL) VALUES ('NikNaks', 14.00 , 212 , 'images/niknaks.jpg');


INSERT INTO COIN (DENOMINATION) VALUES (0.05);
INSERT INTO COIN (DENOMINATION) VALUES (0.10);
INSERT INTO COIN (DENOMINATION) VALUES (0.20);
INSERT INTO COIN (DENOMINATION) VALUES (0.50);
INSERT INTO COIN (DENOMINATION) VALUES (1.00);
INSERT INTO COIN (DENOMINATION) VALUES (2.00);
INSERT INTO COIN (DENOMINATION) VALUES (5.00);
