
CREATE TABLE ITEMS(
 ITEM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 ITEM_NAME VARCHAR(64),
 COST DECIMAL(8,2),
 INVENTORY INT(100),
 IMAGE_URL VARCHAR(100)
);

CREATE TABLE COIN(
 COIN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 DENOMINATION DECIMAL(8,2)
)

